AND = "AND"
OR = "OR"
DEFENSE = "DEFENSE"

ASSET = "asset"
STEP_TYPE = "step_type"
CONDITIONS = "conditions"

TTC_EASY = "EASY_TTC"
TTC_HARD = "HARD_TTC"

REWARD_EASY = "LOW_FLAG_REWARD"
REWARD_MEDIUM = "MEDIUM_FLAG_REWARD"
REWARD_HARD = "HIGH_FLAG_REWARD"
